### PR TITLE
Removed Log4net and use LibLog for logging

### PR DESCRIPTION
**Pull request by madhon**
Sort of Addresses #10 by swapping to [LibLog](https://github.com/damianh/LibLog)
 from the hard reference to log4net.

Have also updated to the nicer testing syntax of Xunit, NSubstitute and Shouldly

### CODE REVIEW

**Comment by shanielh** [comment]
Sweet, Thanks. But why did you update the Readme.md?

**Comment by madhon** [comment]
Opps sorry, thats not an intentional change

**Comment by shanielh** [comment]
Ok. I'll merge it later this weekend. Thanks. 



שני.

**Comment by madhon** [comment]
Excellent, look forward to it thanks

**Comment by shanielh** [comment]
Hi. 

I Reverted to NUnit and the readme file, Everything else is merged :) 

Thanks for your pull request.

**Pull request merged**
